### PR TITLE
Add objects, gofmt

### PR DESCRIPTION
**Pull request by warmans**
Adds some missing objects. Removed some trailing whitespace.

### CODE REVIEW

**Comment by mxmCherry** [comment]
Thanks a lot for contributing, Stefan!

I would like to warn you about a few things that I'm going to change after merge:
- probably, I'll return blank lines within structs later (really later, it does not matter much) because:
	- I think, it makes code a bit more readable (multiline comments stick only to corresponding code lines)
	- I've seen such blanks in your new structs (Regs, Pmp, Deal)
	- it seems, that my gofmt does not cut these blanks, so I suppose, that it's OK
- Rename some types and keys, capitalizing abbreviations (Pmp -> PMP, stands for Private Market Place; Coppa -> COPPA etc.) because:
	- I'm trying to keep such style through the entire repo (for example, Geo struct - RegionFIPS104, ZIP, UTCOffset keys)
	- even if sometimes it does not look too nice, this approach makes naming style a bit more consistent and allows not to think much about "how to camelize it in the most beautiful way"

I strongly discourage you from using this code in production because:
- names may change a bit (mostly camelization)
- types may change a bit (mostly int/float types, for example - int64 -> int16 if 64-bit container is an overkill for key type or something like this)

Actually, I started this repo just to have nice foundation for future RTB-related tasks.
So right now I'm thinking more about making this code as well-organized as possible instead of "just work".
That's why some breaking changes may occur till v1.0 (all TODOs should be implemented and code should be strictly reviewed).

If you would like to start writing production-ready code using this lib right now, I suggest you using GoDep.
If GoDep cannot stick to commit hash - please, notify me somehow to create an intermediate [release](https://github.com/blog/1547-release-your-software)
Or simply use only forked repo for your development.

**Comment by mxmCherry** [comment]
Seems to be done, the only changes were Regs.Coppa -> Regs.COPPA, Pmp -> PMP (still in doubt, if it is right decision, as PMP object referred in OpenRTB 2.3 specs as "Pmp" and not "PMP", but it seems OK) and Deal.At -> Deal.AT (Auction Type).

**Comment by warmans** [comment]
Hi, I'm actually not using this code for anything currently. I just thought the repo needed to exist as the openrtb entities are a pain to implement from scratch. I would agree that you should not worry about breaking changes at this stage in it's development.

Naming conventions are a good idea. Sounds like a sensible approach.

Sorry about the space reformatting. It's annoying, I know. Though I think it may have been gofmt that did it and I'd always recommend following what gofmt thinks is best.

BTW, it'd be good if issues were enabled on this repo.

**Comment by mxmCherry** [comment]
Regarding space reformatting - now it seems to be fine. Probably, I did not pay enough attention to diffs or git merged it preserving those blank lines - don't know exactly, but I'm fully satisfied with current formatting.
Now issues are enabled, thanks for advice.

**Pull request merged**
